/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Designed_Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Vyata
 */
public class AdminEditAddCourse extends javax.swing.JFrame {

    /**
     * Creates new form AdminEditAddCourse
     */
    String courseCode, courseTitle;
    int serialNo;
    DefaultTableModel model;
    public AdminEditAddCourse() {
        super("Add,Edit & Update Course - Administrator | FEEDBACK MANAGEMENT SYSTEM");
        initComponents();
        fetchAvailableCourses();
    }
    
    public void fetchAvailableCourses(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback_management_system","root","");
            
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("SELECT * FROM courses ");
            
            while(rs.next()){
                int serialNo = rs.getInt("ID");
                String courseCode = rs.getString("CourseCode");
                String courseTitle = rs.getString("CourseTitle");
                
                Object[] obj = {serialNo, courseCode, courseTitle};
                model =(DefaultTableModel) tblAvailableCourse.getModel();
                model.addRow(obj);
            }
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void tableBugFix(){
        DefaultTableModel model = (DefaultTableModel) tblAvailableCourse.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableCourse = new rojeru_san.complementos.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        edtCourseID = new app.bolivia.swing.JCTextField();
        edtCourseCode = new app.bolivia.swing.JCTextField();
        edtCourseTitle = new app.bolivia.swing.JCTextField();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        btnAddCourse = new rojerusan.RSButtonMetro();
        btnUpdateCourse = new rojerusan.RSButtonMetro();
        btnBack = new rojerusan.RSButtonMetro();
        btnDeleteCourse = new rojerusan.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 255, 153));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Impact", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN COURSE OPERATION | FEEDBACK MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblAvailableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Course Code", "Course Title"
            }
        ));
        tblAvailableCourse.setAltoHead(30);
        tblAvailableCourse.setColorBackgoundHead(new java.awt.Color(0, 255, 153));
        tblAvailableCourse.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblAvailableCourse.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblAvailableCourse.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tblAvailableCourse.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAvailableCourse.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblAvailableCourse.setFuenteHead(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAvailableCourse.setRowHeight(30);
        tblAvailableCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAvailableCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAvailableCourse);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));

        edtCourseID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 2, 1));
        edtCourseID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        edtCourseID.setPlaceholder("Course ID");

        edtCourseCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 2, 1));
        edtCourseCode.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        edtCourseCode.setPlaceholder("Course Code");

        edtCourseTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 2, 1));
        edtCourseTitle.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        edtCourseTitle.setPlaceholder("Course Title");

        rSButtonMetro1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System_Icons/search(32x32).png"))); // NOI18N
        rSButtonMetro1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        btnAddCourse.setBackground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setForeground(new java.awt.Color(0, 0, 0));
        btnAddCourse.setText("ADD");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnUpdateCourse.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateCourse.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateCourse.setText("UPDATE");
        btnUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCourseActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDeleteCourse.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCourse.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteCourse.setText("DELETE");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COURSE OPERATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCourseTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(edtCourseID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdateCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(edtCourseCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(edtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        setSize(new java.awt.Dimension(1294, 727));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
        if(addCourse()==true){
            javax.swing.JOptionPane.showMessageDialog(this, "Course added successfully.");
            tableBugFix();
            fetchAvailableCourses();
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Course couldn't be added.");
        }
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCourseActionPerformed
        // TODO add your handling code here:
        if(updateCourse()==true){
            javax.swing.JOptionPane.showMessageDialog(this, "Course updated successfully.");
            tableBugFix();
            fetchAvailableCourses();
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Course couldn't be Updated.");
        }
    }//GEN-LAST:event_btnUpdateCourseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminDashboard adminDashboard = new AdminDashboard();
        adminDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
        if(deleteStudent()==true){
            javax.swing.JOptionPane.showMessageDialog(this, "Course deleted successfully.");
            tableBugFix();
            fetchAvailableCourses();
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Course couldn't be deleted.");
        }
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void tblAvailableCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAvailableCourseMouseClicked
        // TODO add your handling code here:
        int rowNo = tblAvailableCourse.getSelectedRow();
        TableModel model = tblAvailableCourse.getModel();
        
        edtCourseID.setText(model.getValueAt(rowNo, 0).toString());
        edtCourseCode.setText(model.getValueAt(rowNo, 1).toString());
        edtCourseTitle.setText(model.getValueAt(rowNo, 2).toString());
    }//GEN-LAST:event_tblAvailableCourseMouseClicked

    public boolean addCourse(){
        boolean courseAdded = false;
        //serialNo = Integer.parseInt(edtCourseID.getText());
        courseCode = edtCourseCode.getText();
        courseTitle = edtCourseTitle.getText();
        
        
        try{
            Connection con = FMSDatabaseConnection.getConnection();
            String sql = "INSERT INTO courses(CourseCode, CourseTitle) VALUES (?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            //ps.setInt(1, studentID);
            ps.setString(1,courseCode);
            ps.setString(2,courseTitle);
                        
            int rowCount = ps.executeUpdate();
            
            if(rowCount>0){
                courseAdded = true;
                //JOptionPane.showMessageDialog(this, "Student Added Successfully.");
            }
            else{
                courseAdded = false;
                //JOptionPane.showMessageDialog(this,"Student couldn't be added.");
            }
            
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null,e);
        }
        return courseAdded;
    }
    
    public boolean updateCourse(){
        boolean studentUpdated = false;
        serialNo = Integer.parseInt(edtCourseID.getText());
        courseCode = edtCourseCode.getText();
        courseTitle = edtCourseTitle.getText();
        
        try{
            Connection con = FMSDatabaseConnection.getConnection();
            String sql = "UPDATE courses SET CourseCode= ?,CourseTitle= ? WHERE ID = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1,courseCode);
            ps.setString(2,courseTitle);
            ps.setInt(3, serialNo);
            
            int rowCount = ps.executeUpdate();
            
            if(rowCount>0){
                studentUpdated = true;
                //JOptionPane.showMessageDialog(this, "Student Added Successfully.");
            }
            else{
                studentUpdated = false;
                //JOptionPane.showMessageDialog(this,"Student couldn't be added.");
            }
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        return studentUpdated;
    }
    
    public boolean deleteStudent(){
        boolean studentDeleted = false;
        serialNo = Integer.parseInt(edtCourseID.getText());
        
        try{
            Connection con = FMSDatabaseConnection.getConnection();
            String sql = "DELETE FROM courses WHERE ID = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, serialNo);
            
            int rowCount = ps.executeUpdate();
            
            if(rowCount>0){
                studentDeleted = true;
                //JOptionPane.showMessageDialog(this, "Student Added Successfully.");
            }
            else{
                studentDeleted = false;
                //JOptionPane.showMessageDialog(this,"Student couldn't be added.");
            }
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        return studentDeleted;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditAddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btnAddCourse;
    private rojerusan.RSButtonMetro btnBack;
    private rojerusan.RSButtonMetro btnDeleteCourse;
    private rojerusan.RSButtonMetro btnUpdateCourse;
    private app.bolivia.swing.JCTextField edtCourseCode;
    private app.bolivia.swing.JCTextField edtCourseID;
    private app.bolivia.swing.JCTextField edtCourseTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojeru_san.complementos.RSTableMetro tblAvailableCourse;
    // End of variables declaration//GEN-END:variables
}
